/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Users', [
      {
        name: 'Yulia',
        email: 'yulya@yulya.com',
        password: '123',
        photo: 'https://ca.slack-edge.com/T03HY1ND24T-U03PQ5P24BU-501689c4085e-512',
        bday: '2000-03-31',
        description: 'Я очень люблю Новый год!',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Guzel',
        email: 'guzel@guzel.com',
        password: '123',
        photo: 'https://ca.slack-edge.com/T03HY1ND24T-U03RYANC822-0db32d860011-512',
        bday: '1998-07-19',
        description: 'Я очень люблю день рождения!',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Sergey',
        email: 'sergey@sergey.com',
        password: '123',
        photo: 'https://ca.slack-edge.com/T03HY1ND24T-U03LHE2QD7H-88c7a8de9391-512',
        bday: '1996-02-27',
        description: 'Я очень люблю Хеллоуин!',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Dima',
        email: 'yara@yara.com',
        password: '123',
        photo: 'https://ca.slack-edge.com/T03HY1ND24T-U03QHPM7Z40-c6c595662fc9-512',
        bday: '1989-02-01',
        description: 'Я очень люблю ходить в бар!',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Aynur',
        email: '123@123.com',
        password: '123',
        photo: 'https://avatars.githubusercontent.com/u/104395473?v=4',
        bday: '1989-02-01',
        description: 'Я очень люблю работать в команде!',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Olya',
        email: 'olya@olya.com',
        password: '123',
        photo: 'https://sun1-54.userapi.com/impg/JeD3ER0Mra8lAkOHJjM1J-_A7hiGYbx0d7w_vA/mMWgO5cEjJo.jpg?size=960x1280&quality=95&sign=731b91381dc913e02b3898f0f6c346a7&type=album',
        bday: '2001-03-18',
        description: 'Я очень люблю дизайн!',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Albina',
        email: 'alya@alya.com',
        password: '123',
        photo: 'https://avatars.githubusercontent.com/u/98209223?v=4',
        bday: '2000-01-26',
        description: 'Я очень люблю путешествовать!',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Vova',
        email: 'vova@vova.com',
        password: '123',
        photo: 'https://proprikol.ru/wp-content/uploads/2020/03/kartinki-rusalochki-ariel-43.jpg',
        bday: '1980-05-21',
        description: 'Я очень люблю фотографии!',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Nona',
        email: 'nona@nona.com',
        password: '123',
        photo: 'https://avatars.githubusercontent.com/u/108142013?v=4',
        bday: '1990-10-20',
        description: 'Я очень люблю своего лабрадора!',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Fil',
        email: 'fil@123.com',
        password: '123',
        photo: 'https://avatars.githubusercontent.com/u/108083490?v=4',
        bday: '1990-10-20',
        description: 'Я очень люблю машины!',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Users', null, {});
  },
};
