/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Owners', [
      {
        wish_id: 1,
        user_id: 2,
        private: false,
        description: 'буду рада!!',
        date: '2022-12-31',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 2,
        user_id: 7,
        private: false,
        description: 'merci',
        date: '2022-11-13',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 3,
        user_id: 3,
        private: false,
        description: 'hi',
        date: '2022-10-10',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 4,
        user_id: 8,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 5,
        user_id: 10,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 6,
        user_id: 3,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 7,
        user_id: 1,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 8,
        user_id: 7,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 9,
        user_id: 5,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 10,
        user_id: 1,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 11,
        user_id: 6,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 12,
        user_id: 2,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 13,
        user_id: 8,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 14,
        user_id: 9,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 15,
        user_id: 3,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 16,
        user_id: 10,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 17,
        user_id: 5,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 18,
        user_id: 4,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 19,
        user_id: 9,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 20,
        user_id: 7,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        wish_id: 21,
        user_id: 7,
        private: false,
        description: 'hi',
        date: '2022-11-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Owners', null, {});
  },
};
